# Generated by Django 3.0.4 on 2020-05-28 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_no', models.IntegerField()),
                ('allocated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DayMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DivisionMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_no', models.CharField(max_length=20)),
                ('allocated', models.IntegerField(default=0)),
                ('curr_slot', models.TimeField(default='9:30')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=20)),
                ('hire_date', models.DateField()),
                ('weight', models.IntegerField(default=10)),
                ('allocated', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LabMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lab_no', models.IntegerField()),
                ('allocated', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SemMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShiftMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_no', models.IntegerField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('break_from_time', models.TimeField()),
                ('break_to_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SubjectMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=20)),
                ('max_lab', models.IntegerField(default=0)),
                ('max_lec', models.IntegerField(default=0)),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_timetable.SemMaster')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_timetable.BatchMaster')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_timetable.Classroom')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_timetable.DayMaster')),
                ('div', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_timetable.DivisionMaster')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_timetable.FacultyMaster')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_timetable.LabMaster')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_timetable.SubjectMaster')),
            ],
        ),
        migrations.AddField(
            model_name='facultymaster',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_timetable.ShiftMaster'),
        ),
        migrations.AddField(
            model_name='facultymaster',
            name='subject',
            field=models.ManyToManyField(related_name='faculties', to='general_timetable.SubjectMaster'),
        ),
        migrations.AddField(
            model_name='divisionmaster',
            name='sem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_timetable.SemMaster'),
        ),
        migrations.AddField(
            model_name='divisionmaster',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_timetable.ShiftMaster'),
        ),
        migrations.AddField(
            model_name='batchmaster',
            name='div',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_timetable.DivisionMaster'),
        ),
    ]
