# Generated by Django 3.0.1 on 2020-06-07 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_timetable', '0003_auto_20200528_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablemaster',
            name='laborlec',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timetablemaster',
            name='slt_end',
            field=models.TimeField(default='9:30'),
        ),
        migrations.AddField(
            model_name='timetablemaster',
            name='slt_start',
            field=models.TimeField(default='9:30'),
        ),
        migrations.AlterField(
            model_name='timetablemaster',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general_timetable.BatchMaster'),
        ),
        migrations.AlterField(
            model_name='timetablemaster',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general_timetable.Classroom'),
        ),
        migrations.AlterField(
            model_name='timetablemaster',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general_timetable.LabMaster'),
        ),
    ]
