# Generated by Django 3.2.4 on 2022-09-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_timetable', '0004_auto_20200607_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmaster',
            name='lab_rm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='lec_rm',
            field=models.IntegerField(default=0),
        ),
    ]
